config/routes.rb
Listenlater::Application.routes.draw do

  resources :feeds do
    resources :bookmarks
  end

  root to: "feeds#new"

end

app/models/bookmark.rb
class Bookmark < ActiveRecord::Base
  belongs_to :feed
  validates :location, presence: true
end

app/models/extensions/uuid.rb
module Extensions
  module UUID
    extend ActiveSupport::Concern

    included do
      set_primary_key 'id'
      before_create :generate_uuid

      def generate_uuid
        self.id = UUIDTools::UUID.random_create.to_s
      end
    end
  end
end

app/models/feed.rb
class Feed < ActiveRecord::Base
  include Extensions::UUID
  has_many :bookmarks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  before_filter :load_feed

  def create
    @bookmark = @feed.bookmarks.new(params[:bookmark])

    respond_to do |format|
      if @bookmark.save
        format.html { redirect_to feed_url(@bookmark.feed) }
      else
        format.html { redirect_to feed_url(@bookmark.feed), alert: 'A file URL could be very helpful here... ;)' }
      end
    end
  end

  def destroy
    @bookmark = @feed.bookmarks.find(params[:id])
    @bookmark.destroy

    respond_to do |format|
      format.html { redirect_to feed_url(@bookmark.feed) }
    end
  end

  private

  def load_feed
    @feed = Feed.find(params[:feed_id])
  end

end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController

  def show
    @feed = Feed.find(params[:id])
    @bookmarks = @feed.bookmarks.reverse

    respond_to do |format|
      format.html
      format.atom
    end
  end

  def new
    @feed = Feed.new

    respond_to do |format|
      format.html
    end
  end

  def create
    @feed = Feed.new(params[:feed])

    respond_to do |format|
      if @feed.save
        format.html { redirect_to @feed }
      else
        format.html { render action: "new" }
      end
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/views/application/_flashes.html.haml
#flashes
  - flash.each do |key, value|
    .alert{class: "alert-#{key}", title: key.to_s.humanize}
      %p
        = value
    %br

app/views/application/_footer.html.haml
%footer
  %p.centered
    listen l8r is a sunday side dish, served by
    = link_to "Railslove", "http://railslove.com"
    &mdash;
    and boy is it
    = link_to "Open Source", "https://github.com/railslove/listenl8r"
    %br
    %small
      = link_to "Follow @ll8r on Twitter", "http://twitter.com/ll8r"
      and give us your feedback
      &middot;
      = link_to "Imprint", "http://www.railslove.com/impressum.txt"

app/views/application/_head.html.haml
%head
  %meta{ charset: 'utf-8' }/
  %meta{ 'http-equiv' => 'X-UA-Compatible', content: 'IE=edge,chrome=1' }/

  %title listen l8r &mdash; your private podcast feed
  %meta{ name: 'description', content: '' }/
  %meta{ name: 'author', content: '' }/

  -# Mobile viewport optimized: h5bp.com/viewport
  %meta{ name: 'viewport', content: 'width=790' }/

  -# Place favicon.ico and apple-touch-icon.png in the root directory: mathiasbynens.be/notes/touch-icons

  = javascript_include_tag "//ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"
  = stylesheet_link_tag "application"
  = csrf_meta_tag

  - if Rails.env.production?
    :javascript
      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-35924093-1']);
      _gaq.push(['_trackPageview']);

      (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();

app/views/application/_header.html.haml
%header
  - if @feed && !@feed.new_record?
    %h1= link_to image_tag("listenl8r.png"), root_url
    %h2
      = link_to "This is your private podcast feed.", feed_url(@feed, format: "atom")
      %br
      Add audio files from the web to start listening l8r.
    %hr

app/views/feeds/new.html.haml
%h1.logo
  = image_tag "listenl8888r.png"
= form_for @feed do |f|
  %button.btn.btn-danger.btn-large{type: "submit"}
    Start your private podcast feed

app/views/feeds/show.html.haml
:javascript
  $(document).ready(function() {
    $('#bookmark_location').focus();
  });
= form_for Bookmark.new, url: feed_bookmarks_path(@feed) do |f|
  .control-group
    .controls
      = f.text_field :location, placeholder: "http://example.com/podcast.mp3", class: "input-xxlarge location"
  .control-group#title_group
    = f.label :title, "File Title (optional)", class: "control-label"
    .controls
      = f.text_field :title, placeholder: "Example Podcast, Episode 23 — May 18, 2012", class: "input-xxlarge"
  .control-group
    .controls
      %button.btn.btn-danger{type: "submit"}
        %i.icon-arrow-down.icon-white
        Add to feed
      %button.btn{onclick: "$('#title_group').show();$('#title_group').find('input').focus();$(this).hide();return false"}
        %i.icon-plus
        Add title

- if @bookmarks.any?
  %table.table.table-striped.table-condensed
    %thead
      %tr
        %th Added
        %th Title
        %th URL
        %th
    %tbody
      - @bookmarks.each do |bookmark|
        %tr
          %td= l bookmark.created_at, format: :short
          %td= bookmark.title
          %td= link_to bookmark.location, bookmark.location
          %td= button_to "remove", feed_bookmark_path(@feed, bookmark), method: :delete, class: "btn btn-danger btn-mini"

app/views/layouts/application.html.haml
!!! 5
- html_tag class: 'no-js', lang: 'en' do
  = render 'head'

  %body{ class: "controller-#{ controller.controller_name } action-#{ controller.action_name }" }

    #container
      = render 'header'
      = render 'flashes'
      #main{ role: 'main' }
        .content
          = yield

      = render 'footer'